"""
Basic configurations for CLUBench.
"""

import os.path as osp

ROOT_DIR = osp.dirname(osp.abspath(__file__))
DATA_DIR = osp.join(ROOT_DIR, 'datasets')
HPC_DIR = osp.join(ROOT_DIR, 'hpc')


DATASETS = [

    # tabular ==========================================
    'echocardiogram.npz', 
    'skillcraft1_master_table_dataset.npz', 
    'breast_cancer_wisconsin_original.npz', 
    'smoker_condition.npz', 
    'glass_identification.npz', 
    'statlog_image_segmentation.npz', 
    'planning_relax.npz', 
    'customer_classification.npz',
    'pima_indians_diabetes_database.npz', 
    'mobile_price_classification.npz',
    'spambase.npz',
    'rice_seed_gonen_jasmine.npz',
    'heart_attack_analysis_prediction_dataset.npz', 
    'user_knowledge_modeling.npz', 
    'world12d.npz', 
    'pumpkin_seeds.npz', 
    'iris.npz',
    'wine.npz', 
    'letter_recognition.npz',
    'mammographic_mass.npz',
    'breast_tissue.npz',
    'hepatitis.npz', 
    'predicting_pulsar_star.npz',
    'breast_cancer_wisconsin_prognostic.npz',
    'wireless_indoor_localization.npz', 
    'date_fruit.npz',
    'zoo.npz',
    'htru2.npz',
    'ionosphere.npz',
    'music_genre_classification.npz', 
    'spectf_heart.npz',
    'rice_dataset_cammeo_and_osmancik.npz',
    'ph_recognition.npz',
    'banknote_authentication.npz', 
    'wine_quality.npz',
    'cardiovascular_study.npz',
    'statlog_german_credit.npz',
    'boston.npz',
    'seismic_bumps.npz', 
    'dry_bean.npz',
    'credit_risk_classification.npz',
    'epileptic_seizure_recognition.npz',
    'website_phishing.npz', 
    'optical_recognition_of_handwritten_digits.npz',
    'siberian_weather_stats.npz', 
    'orbit_classification_for_prediction_nasa.npz',
    'magic_gamma_telescope.npz',
    'raisin.npz',
    'patient_treatment_classification.npz', 
    'fetal_health_classification.npz',
    'dermatology.npz',
    'secom.npz',
    'paris_housing_classification.npz',
    'seeds.npz', 
    'wine_customer.npz',
    'crowdsourced_mapping.npz',
    'durum_wheat_features.npz',
    'classification_in_asteroseismology.npz', 
    'birds_bones_and_living_habits.npz',
    'microbes.npz',
    'image_segmentation.npz',
    'water_quality.npz',
    'insurance_company_benchmark.npz', 
    'harbermans_survival.npz',
    'yeast.npz',
    'heart_disease.npz',
    'ecoli.npz',
    'extyaleb.npz', 
    'breast_cancer_coimbra.npz',
    'student_grade.npz',
    'human_stress_detection.npz',
    'fraud_detection_bank.npz',
    'pen_based_recognition_of_handwritten_digits.npz', 
    'diabetic_retinopathy_debrecen.npz',
    'pistachio.npz',
    'turkish_music_emotion.npz',
    'parkinsons.npz',
    'weather.npz', 
    'blood_transfusion_service_center.npz',
    'mfeat-karhunen.npz', 
    'mfeat-factors.npz',
    'wall-robot-navigation.npz',
    'Waveform.npz', 
    'gas-drift.npz',
    'mfeat-morphological.npz',
    'JapaneseVowels.npz',
    'rmftsa_sleepdata.npz',
    'first-order-theorem-proving.npz',
    'gina_prior2.npz',
    'fabert.npz',
    'dilbert.npz',
    'synthetic_control.npz',
    'Drug Consumption.npz',
    'shuttle.npz',
    'tr45.wc.npz',
    'steel-plates-fault.npz',
    'fbis.wc.npz',
    'mfeat-fourier.npz',
    'vehicle.npz',
    'micro-mass.npz',
    'ISOLET.npz',
    'poker-hand.npz',
    'tamilnadu-electricity.npz',

    # image ============================================
    'mnist64.npz',
    'MNIST_CLIP.npz',
    'fashion_mnist.npz',
    'FashionMNIST_CLIP.npz',
    'cifar10.npz', 
    'CIFAR10_CLIP.npz',
    'coil20.npz', 
    'COIL20_CLIP.npz',
    'labeled_faces_in_the_wild.npz',
    'flickr_material_database.npz',
    'street_view_house_numbers.npz',
    'har.npz', 
    'Indian_pines.npz',
    'satellite_image.npz',
    'olivetti_faces.npz',
    'PCam.npz',

    # text ====================================================
    'cnae9.npz',
    'imdb.npz',
    'hate_speech.npz',
    'sentiment_labeld_sentences.npz', 
    'sms_spam_collection.npz',
    'wos.npz',
    'enron.npz',
    'reuters.npz',
    '20newsgroups.npz',
    
    # bioinfo =================================================
    'Mouse_retina.npz',
    'Campbell.npz',
    'Baron Human.npz',
]

